### PR TITLE
Test configuration and other little things

### PR DESCRIPTION
**Pull request by vital-edu**
This PR has the following goals:
- **README**: add information about configuration and running of the application to attract new contributors
- **Tests**: configure the the Jest Testing Framework as first step to the long task of test the entire application
- **Continuos Integration**: add initial configuration to provide information about the status of the current build. This is important to determine if a PR it is safe to accept (but it is useless without a huge improvement of the code testing)
- assigned: add basic code analysis to future improvements in the code quality. It is necessary to think what kind of static analises the project needs and confiture the eslint to accomplish this goal.

This PR is assigned by:
- DylanGuedes <djmgguedes@gmail.com>
- Eduardo Vital <vitaldu@gmail.com>
- Gustavo Cavalcante <gustavo.cavalcante.oliveira@live.com>
- MatheusFerraz <matheus_ccmf@yahoo.com.br>
- Tallys Martins <tallysmartins@gmail.com>>
- Wilton Rodrigues <braywilton@gmail.com>

**Observation**: The badge of the Travis will crash until some mantainer of the repository authorize the Travis integration.

### CODE REVIEW

**Comment by mbjorkegren** [comment]
Hi Eduardo, thanks for the PR!

It'll be great to have some testing tools to work with!

I just ran a copy of the branch, but it looks like the rendered result of the refactored privacy.js is not identical to the original version.  There is a difference starting with the second paragraph. It's difficult to see the difference in the diff, but it's apparent if you compare in a rendered side-by-side with the original.
You can see the original here for comparison: https://pol.is/privacy

Also please be sure that everyone who contributed code has signed the contributor agreement: https://pol.is/contrib

Thanks!

**Comment by vital-edu** [comment]
Everyone accepted the terms and we reverted the modifications in the Privacy Policy.

We did the test more as a concept and unfortunately we did not pay attention that the test passed but the page was modified, we are sorry about that.

**Comment by mbjorkegren** [comment]
No problem at all, did Tallys also contribute code to this one? I looks like he might not have signed the contrib agreement yet.

**Comment by vital-edu** [comment]
Yeah, Tallys hadn't signed yet.
I think that he did right now. 

Please, may you give me a way to chat with you about some problems that I am facing of?

Does not need to be by now(I will be travelling this weekend), but I really need your help to setup the polisServer. I got the polisServer running with thepolisClientAdmin but I can't make the registration/login. I think that it is some configuration that it is missing.

**Comment by vital-edu** [comment]
Is there anything that we need to change?

**Comment by mbjorkegren** [comment]
No, It looks great, thank you.

**Pull request merged**
